feat: user dropdown
whizzes/quicklink-dashboard pull request #19
Opened 2023-02-16 22:25 UTC by Michael-Liendo

2023-02-16 23:26 UTC, EstebanBorai requested changes
Some help with types and remove not required nav item.
Remaining bits are looking great!

2023-02-16 23:26 UTC, EstebanBorai commented on src/routes/(app)/components/Navbar/Profile.svelte
> +          </li>
I think we dont need this as of today, given that settings page doesnt exists

2023-02-16 23:26 UTC, EstebanBorai commented on src/lib/actions/click-outside.ts
> +      node.dispatchEvent(new CustomEvent('clickOutside', node));
I think the `CustomEventInit` is not required.

```suggestion
      node.dispatchEvent(new CustomEvent('clickOutside'));
```

2023-02-16 23:26 UTC, EstebanBorai commented on src/lib/actions/click-outside.ts
> +    if (node && !node.contains(event.target) && !event.defaultPrevented) {
Here we can assume this value is a `Node`.

```suggestion
    if (node && !node.contains(event.target as Node) && !event.defaultPrevented) {
```

2023-02-16 23:26 UTC, EstebanBorai commented on src/lib/actions/click-outside.ts
> +export function clickOutside(node: any) {
`node` here is actually a `HTMLElement`

```suggestion
export function clickOutside(node: HTMLElement) {
```

2023-02-17 00:17 UTC, Michael-Liendo commented
Thanks for the help!

2023-02-17 00:28 UTC, EstebanBorai commented
> Thanks for the help!

Anytime!

2023-02-17 00:29 UTC, EstebanBorai approved these changes

2023-02-17 00:29 UTC, merged